spring:
  profiles:
    active: dev
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  config:
    import: classpath:.env[.properties]
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      connection-timeout: 10000 #maximum number of milliseconds that a client will wait for a connection
      minimum-idle: 10 #minimum number of idle connections maintained by HikariCP in a connection pool
      maximum-pool-size: 30 #maximum pool size
      idle-timeout: 10000 #maximum idle time for connection
      max-lifetime: 1000 # maximum lifetime in milliseconds of a connection in the pool after it is closed.
      auto-commit: true #default auto-commit behavior
      leak-detection-threshold: 200
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    show-sql: false
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob:
          non_contextual_creation: true
server:
  port: 8080

springdoc:
  api-docs:
    version: openapi_3_1
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

api:
  base-path: /api/v1

logPathLocal: ${LOGS_FOLDER_PATH}/report_%s.log

